### ISSUE TITLE
Input topic ARN instead of topic name?

### ISSUE THREAD

**Issue by RulerOf** [trussworks/terraform-aws-guardduty-notifications#3]
I was looking to pair your module with [this Slack notifier](/terraform-aws-modules/terraform-aws-notify-slack), but can't without forking because this module wants a friendly name for the SNS topic instead of the ARN.

Since this module is small I'm probably going to just cut and paste the relevant portions that I need directly into my project, but I wanted to let you know that this mismatch affects my use case. I can't come up with a patch that will allow it to accept both without some significant work and a lot of ugly `count`ing.

**Comment by RulerOf** [comment]
The example you've supplied only works if you create the Slack SNS topic resources in a Terraform run prior to actually inserting this GuardDuty module into your terraform project. The problem is due to [how Terraform data sources work](https://www.terraform.io/docs/configuration/data-sources.html#data-resource-behavior)—since the plaintext value of [`module.guardduty-notifications.data.aws_sns_topic.main.name`](https://github.com/trussworks/terraform-aws-guardduty-notifications/blob/master/main.tf#L26) is known at the start of the Terraform run, the AWS provider will attempt to look up the SNS topic ARN prior to actually creating any resources at all. The data lookup will fail, and Terraform will exit with an error.

**Comment by dynamike** [comment]
Ah! We've run into this issue before. It's a change in behavior starting in Terraform 0.12 that's we've come across in another one of our modules. https://github.com/hashicorp/terraform/issues/22730

The fix is to pull all data source look ups out of the module and pass in the resource object, in this case the entire sns_topic in as a variable. We should have a fix shortly.

**Comment by RulerOf** [comment]
That sounds good. 

Again, I suggest you just accept the topic ARN, and that will present a natural fit with the other module I mentioned. Maintaining backward compatibility with accepting the topic name is possible but it’s a lot of work and isn’t really desirable IMO, so I’d recommend doing this as a breaking change because it’d be a very fast fix.

**Comment by dynamike** [comment]
Sorry for the late response. This should be resolved with https://github.com/trussworks/terraform-aws-guardduty-notifications/pull/6/files
